### ISSUE TITLE
Add Flag to MasterFile to Indicate Interestingness

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#103]
Dan wrote:

Yesterday you asked me if I could think of any additions or changes to Tracksys that might facilitate staff contributions to the department's social media platforms. This morning I thought of one. When I talked to James and Jacob last week about ways the students could contribute to DCS social media sites they mentioned that it would help if there was a way for students to flag images as "interesting" during the scanning and QA process. Then student supervisors and/or full-time staff could review the flagged items and upload select images onto Pinterest and the other social media platforms when they had the time to do so. This process would likely reduce the time staff spend on identifying candidate social media images and give more senior staff some control over the quality of the images that are posted and the timing of the posts.

Would it be possible for you to add an "Is it interesting?" attribute (I'm sure there is a better title, but I can't think of one now) to the master file entity in Tracksys? I thought it would be helpful if student's who work with images in Tracksys could click on a button to flag the item as interesting when they first see it. Then supervisors and full-time staff could quickly search for candidate images with a query that identifies master files in Tracksys that are "interesting", published before 1923, and in the digital library.

**Comment by louffoster** [comment]
similar request received from Lois - but a bit more detailed; add ability for users to tag items in tracksys with key words. interesting is just a subset of this. This feature is tracked elsewhere, so closing out this issue
