### ISSUE TITLE
Order Status Changes

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#11]
Special Collection public services staff want orders to be more explicit in their status.  The only status that an order explicitly has is 'awaiting fee response'.  But for display purposes, it should include information about its children units and their status.  So an order can be awaiting a fee response, while its units are awaiting condition review, copyright review or a combination of the two.  Staff want to have a better understanding of what is going on with the order and its composite units for the purposes of assessing where the whole is in their pre-digitization workflow.

**Comment by louffoster** [comment]
added a brief status message to the approval workflow panel
