### ISSUE TITLE
Order approved date not filling in consistently.

### ISSUE THREAD

**Issue by JocelynTriplett** [uvalib/tracksys#135]
When going through our workflow of processing slide units, we've noticed that sometimes the order will be marked by the system as approved and the date filled in, and sometimes it won't. We're not sure what's up. Ask Jocelyn for further information.

**Comment by louffoster** [comment]
Ensured that any time an order is approved, the date is set. There is also an order status change audit log generated. It can be viewed by hovering over the info icon to the right of the order status
