### ISSUE TITLE
MasterFiles assigned to Components lose RDF relation to Bibl

### ISSUE THREAD

**Issue by MatthewStephens** [uvalib/tracksys#141]
CDeane reported a problem with uva-lib:760484 (Unit 2498, Bibl 1641), specifically, pages were missing from the Virgo digital book view.  Analysis revealed that the MasterFiles had 'isConstituentOf' but lacked 'hasCatalogRecordIn' from the RELS_EXT datastream.  The latter relation binds a MF to a bibliographic record, as it exists in Fedora.  The former binds it to a Component, and thus a hierarchy.

The Hydra#rels_ext method tests MasterFiles: if they belong to a Component, the former triple is added, if not, the latter.  We need to be able to add both on occasion, so the logic of this method must change.

I manually altered the rels_ext for the masterfiles in unit 2498, and they are stored in the TS database, overriding the call to Hydra#rels_ext for these items.  They should be removed when this issue is resolved, or kept in case the issue cannot be resolved as described.

**Comment by louffoster** [comment]
fedora and rels_ext are no longer used. components being retired. closing issue
