### ISSUE TITLE
Repair Component#descendant_master_files

### ISSUE THREAD

**Issue by MatthewStephens** [uvalib/tracksys#147]
Newer components aren't getting parent_component_id attributes, and this means we need to refactor the method returning all masterfiles in a hierarchy.

something like this should do:

def descendant_master_files
  descendants=self.descendants
  descendants.reduce([]) {|result,c| result << c.master_files if c.master_files != nil }
  descendants.flatten!
end

**Comment by louffoster** [comment]
components being retired; not fixing
