### ISSUE TITLE
Remove options for choosing resolution/use case from patron form

### ISSUE THREAD

**Issue by cmm2t** [uvalib/tracksys#156]
Please remove from the patron form the option for choosing use case, which then sets the resolution provided to the researcher.  The default value sent by the form to the database should become "Personal Research", and a place for indicating special needs if 300dpi jpegs are not sufficient should be allowed.  I think you can use the special instructions field for this, so no new fields need to be created.  I think you will need to tweak the wording on the patron form to make all of this clear though.  Staff will still need to be able to change the resolution on the admin side if the patron actually does need tiffs for a reason that is approved by the powers that be, so that will probably not require a change on the admin side, methinks.  Other things may get teased out during this issue resolution that need to be tweaked that are not obvious to me now.  
Bradley wants this to take a fairly high priority, as this will affect the vetting process for Special Collections and us, and this is something he has just worked out with Spec Coll staff.  You can query him for specifics on when he wants it done, but asap is what I know at this point.

Christina

**Comment by louffoster** [comment]
options have recently be re-organized by Bradely, and include new legal text. Does't seem to be any issues
