### ISSUE TITLE
Orders to be switched to 'completed' status

### ISSUE THREAD

**Issue by Lorrie** [uvalib/tracksys#157]
Internal orders that do not have deliverables but are complete; need to identify and update order status to closed. Current orders identified for closing: 6939, 6438, 6719, 6512, 6784, 7093, 6601, 6654,  Use archiving date to determine completion per J. Triplett via AIM 11/14/2013.

**Comment by louffoster** [comment]
Recently, a script has been run against orders to update those that could be identified as completed as such. In addition, the workflow has been changed to flag orders as complete when specific events occur.
