### ISSUE TITLE
refine capitalization of customer.first_name in PDFs

### ISSUE THREAD

**Issue by MatthewStephens** [uvalib/tracksys#161]
Some order customers have titles or corporate names that are being mis-handled when capitalized.  See Order.find(1172) and Order.find(7131) for examples.

Patch the Customer class or the PDF generator (preferable the first) to prevent this sort of thing from happening:
# <Customer id: 53, department_id: nil, academic_status_id: 1, heard_about_service_id: nil, last_name: "Urchuegua", first_name: "Dr. Cristina", email: "Triosonate@mwi.uzh.ch", created_at: "2009-04-03 22:10:19", updated_at: "2009-07-29 16:07:59", master_files_count: 1674, orders_count: 5>

"Dear #{@customer.first_name.capitalize} #{@customer.last_name.capitalize}, \n\n"
"Dear Dr. cristina Urchuegua, \n\n"

**Comment by louffoster** [comment]
this appears to be done
