### ISSUE TITLE
Making modifications to individual masterfiles in TS and on Stornext

### ISSUE THREAD

**Issue by cmm2t** [uvalib/tracksys#162]
I occasionally need to change the order of masterfiles within a unit after it has been finalized.  Sometimes these changes are major and it would be easier to just delete it and refinalize the item (including deleting images from Stornext, etc.).  Sometimes it's simply a matter of changing the order of some of the files and fixing that on Stornext as well.  What's the most logical way to approach this problem?  I hate to ask a developer to take time away to fix these kind of issues.

**Comment by louffoster** [comment]
The unit UI is now capable of renaming/renumbering, adding and deleting individual master files
