### ISSUE TITLE
Documenting cron jobs, snapshots, etc.

### ISSUE THREAD

**Issue by cmm2t** [uvalib/tracksys#178]
I would like to see us document in as brief but informative a way as possible all of the cron jobs relevant to DCS work, all of the snapshot settings on the server, anything else like this that might affect our workflow and our ability to create and deliver digital orders.  I'm not sure what the full list may be, but I do not know for certain how long items are kept in the ready_to_delete folders on digiserv-production and digiserv-migration, and I'm not certain how long the zip files are left up on digiserv-delivery for the patrons.  I also do not know what we are using to zip them.

**Comment by louffoster** [comment]
migrating this issue to jira
