### ISSUE TITLE
update XML data streams of components should perhaps propogate to master_files

### ISSUE THREAD

**Issue by sdm7g** [uvalib/tracksys#184]
In fixing/updating Reed guide component, I discovered that the master_files belonging to a component need their RELS_EXT updated if the master_file component assignments have changed -- otherwise
they disagree.  Perhaps update-all-xml should propagate to master_files ( like units already do ). 
[ 2. Maybe also propagate to child components ? ]

**Comment by louffoster** [comment]
no longer valid; workflow refactored
