### ISSUE TITLE
dependencies for ingest_rels_ext & ingest_solr_doc may be backwards

### ISSUE THREAD

**Issue by sdm7g** [uvalib/tracksys#190]
:ingest_rels_ext chains to :ingest_solr_doc 
  **# Since the creation of a solr <doc> now requires both the rels-ext and descMetadata of an object, we must create both before a message is sent to ingest_solr_doc**
https://github.com/uvalib-dcs/tracksys/blob/master/app/processors/ingest_rels_ext_processor.rb#L43-L45
but :ingest_solr_doc does not call :ingest_rels_ext first. 
From the comment in the code, and to avoid generating the wrong solr docs, it seems that it ought to be the other way around. If you ask to update the solr doc, it ought to update the rels_ext  dependency first.
( I was tripped up on this on updating _Our Mountain Work_ )

**Comment by louffoster** [comment]
no longer valid; workflow refactored
