### ISSUE TITLE
record showing MCGR-VAULT location

### ISSUE THREAD

**Issue by sdm7g** [uvalib/tracksys#191]
_( See email with that subject from Heather forwarded by Christina and Jocelyn )_

> Hi Guys,
> 
> Could you take a look at this on Monday? There are a couple of differences in the Virgo display that  seem to have happened recently. Christina's note below, and format is suddenly showing up as Ebook for a lot of the McGregor items.
> 
> Jocelyn
> 
> > The following items show the following in their records for the digital surrogate:
> > Location Special Collections MCGR-VAULT
> > 
> > Which has Heather concerned.  They don’t want them to show “Vault” as a location.  
> > 
> > Can you sort out why this is happening with some items but not others?  Can we fix this?
> > This is probably not all of them—just the ones I found in a quick search.
> > 
> > Thanks,  Christina
- http://search.lib.virginia.edu/catalog/uva-lib:2496176
- http://search.lib.virginia.edu/catalog/uva-lib:2506758
- http://search.lib.virginia.edu/catalog/uva-lib:2505639
- http://search.lib.virginia.edu/catalog/uva-lib:2503673
- http://search.lib.virginia.edu/catalog/uva-lib:2497594
- http://search.lib.virginia.edu/catalog/uva-lib:2473546
- http://search.lib.virginia.edu/catalog/uva-lib:2473545
- http://search.lib.virginia.edu/catalog/uva-lib:2466880
- http://search.lib.virginia.edu/catalog/uva-lib:2466833
- http://search.lib.virginia.edu/catalog/uva-lib:2422511

**Comment by sdm7g** [comment]
Nothing has changed on our (Tracksys) end recently - perhaps there has been a change in Virgo that has changed the display. 

The Location value is from the physical items MARCxml record. It's being propagated to the MODS record for the digital item, and from there being passed to the Solr record. If we want to remove them,
then we probably only want to remove them from the latter. That looks like a simple change, but we need to investigate the extent further: will we have to reindex ALL of our digital DL items after this change ? 

https://github.com/uvalib-dcs/uva_fedora_transformations/blob/master/defaultModsTransformation.xsl#L667-L671

We probably also want to remove the (physical) call number from the digital surrogate display.
We need to investigate what other fields need to be removed.

**Comment by louffoster** [comment]
no longer an issue with new iiif virgo display and merged physical/digital view
