### ISSUE TITLE
Clean up & refactor Config URLs and other embedded URLs

### ISSUE THREAD

**Issue by sdm7g** [uvalib/tracksys#192]
I've had to make several fixes in different places when SOLR URLs changed. 
Not all of the instances use constants from the config files, or else they append something to those constants.  We should refactor those config values and their mentions to try to get one point of change to changes to backend URLs.  ( More will be coming when we migrate to Fedora 4 )

**Comment by louffoster** [comment]
Many URLs have been retired. The remaining ones are all set in an application config file. A template is found here: config/application.yml-TEMPLATE
