### ISSUE TITLE
spurious Errors in move_completed_directory_to_delete_directory_processor

### ISSUE THREAD

**Issue by sdm7g** [uvalib/tracksys#193]
It looks like there should be a Dir.exists? guard around this call:
https://github.com/uvalib/tracksys/blob/master/app/processors/move_completed_directory_to_delete_directory_processor.rb#L51

Apparently, sometimes the students can accidentally drag one of those folders out of place, but they don't have the permission to drag it back again. (Odd?) 

The processor will scan all of these subdirectories of either digiserv_production/scan or /digiserv-migration/scan looking for the unit directory, finishing when it has found it. 
PRODUCTION_SCAN_SUBDIRECTORIES = ['01_from_archive', '10_raw', '40_first_QA', '50_create_metadata', '60_rescans_and_corrections', '70_second_qa', '80_final_qa', '90_make_deliverables', '101_archive', '100_finalization']
https://github.com/uvalib/tracksys/blob/master/config/environment.rb#L34

If it finds the unit dir before it hits a non-existent directory it will succeed. 
If it hits a non-existent directory first, it fails. 

The specific directory and error message it yields have been different over time.

**Comment by louffoster** [comment]
This job has been rewritten, and this problem fixed
