### ISSUE TITLE
solr doc stylesheets 

### ISSUE THREAD

**Issue by sdm7g** [uvalib/tracksys#194]
If there is an error in the XSLT stylesheet that is sent to SAXON servlet, it can return a partial and not well formed SOLR add XML doc. This seems to gum up the works for Bob Haschert's reindexing scripts. One bad doc blocks the process for the rest.  Need to add a guard that checks state of XML returned from SAXON servlet and NOT post to solr if it's not well formed.  

The specific failure that demonstrated this is a separate issue:
https://github.com/uvalib/uva_fedora_transformations/issues/7

**Comment by louffoster** [comment]
the whole nightly ingest has been re-worked. A single failure will not stop others. Also; the deaultModsTransfor is no longer used as tracksys no longer produces the solr for items from sirsi
