### ISSUE TITLE
Bibl::VIRGO_FIELDS duplicate field "copy" 

### ISSUE THREAD

**Issue by sdm7g** [uvalib/tracksys#195]
The seems to be a duplication of 'copy' 
( Will remove ASAP, but I found it in the middle of debugging something else, so note here. )

https://github.com/uvalib/tracksys/blob/master/app/models/bibl.rb#L9

9:  VIRGO_FIELDS = ['title', 'creator_name', 'creator_name_type', 'call_number', 'catalog_key', 'barcode', 'copy', 'date_external_update', 'location', 'citation', 'year', 'year_type', 'location', 'copy', 'title_control', 'date_external_update', 'cataloging_source']

**Comment by louffoster** [comment]
no longer valid; Bibl has been refactored into metadata and most fields no longer cached
