### ISSUE TITLE
Add multi-select capabilities for select filters

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#26]
Javascript library Chosen seems like an excellent candidate.  Highly considering 'multi-select' option.

http://harvesthq.github.com/chosen/

**Comment by louffoster** [comment]
This was not requested in the 2017 searching/filtering analysis. Closing.
For future reference, this requires nothing special to do; just add a flag to the filter like this:

`filter :department, :as => :select, multiple: true`

but UI is kinda ugly and wonky
