### ISSUE TITLE
Add ability to Increase Maximum Number of Records

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#30]
Rather than being tied into the default return of 30 records per page, there should be an additional button, presumably to the right of "Last" that allows the user to increase the config.per_page number (currently set to 30).  In order to avoid overloading the database, perhaps we should max the results out at 500?  1000?

**Comment by louffoster** [comment]
just add something like: `config.per_page = [20, 50, 100, 200] ` to each resource. Done
