### ISSUE TITLE
Orders should have a 1:1 relationship with Invoices

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#46]
There are currently a handful of orders with more than 1 invoice.  This makes it more difficult to calculate for a future report of "Unpaid orders" which will be useful for Jeanne.  Change this relationship and then make a new report on the Admin::Dashboard to allow all users to explore both how many orders are unpaid but how much money is owed to Digitization Services.

**Comment by louffoster** [comment]
this 1:1 relationship is now enforced in the back-end processing, and can no longer be violated
