### ISSUE TITLE
Give user the ability to choose the number of results per page

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#5]
Currently, the number of hits per page is the default value set either in initializers/active_admin.rb or on a per resource base.  See the following for more details:

https://github.com/gregbell/active_admin/wiki/How-to-modify-pagination-size

I would like to give the user the ability to change the number of results they can see in one view.

**Comment by louffoster** [comment]
active admin limitation. added a way to page through unit master files or view all. 
view all in other contexts is not possible; data set is too large
