### ISSUE TITLE
Scope counts are inconsistent with filtered results

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#6]
The scope counts become correct if you click on the scope itself (clicking causes a reset and a recount).  This issue is listed as part of the 0.4.0 release, but hasn't come out yet.

https://github.com/gregbell/active_admin/issues/805

Keep in mind as a known issue that will be updated soon.

**Comment by louffoster** [comment]
currently on activeadmin 1.1.0 and issue is resolved
