### ISSUE TITLE
MoveCompletedDirectoryToDeleteDirectoryProcessor messages not saving

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#62]
When uploading FKL material (i.e. unit_id is nil), the messages are not saving to the DB.  

AutomationMessageProcessor: Can't save message to database: Validation failed: Messagable can't be blank
Message was:
{"messagable_id":null,"messagable_type":"Unit","pid":null,"message_type":"success","app":"tracksys","processor":"MoveCompletedDirectoryToDeleteDirectoryProcessor","workflow_type":"delivery","message":"All files associated with 20120608ARCH has been moved to /digiserv-production/ready_to_delete/from_stornext_manual_upload."}

**Comment by louffoster** [comment]
closing per above comment
