### ISSUE TITLE
Investigate oddball ActiveRecord::Relation behavior

### ISSUE THREAD

**Issue by MatthewStephens** [uvalib/tracksys#75]
I seem to keep getting the wrong ead_id_att data when building lists of things.  Database record MAY have d1e9309 for this record, which is incorrect, but the ruby methods are returning the correct value in some circumstances.

 => #<Component id: 14753, component_type_id: 14, parent_component_id: 14752, title: "General Correspondence", label: nil, date: nil, content_desc: "General Correspondence", idno: nil, barcode: nil, seq_number: nil, pid: "uva-lib:1331041", created_at: "2011-06-23 10:19:13", updated_at: "2012-06-29 20:17:04", desc_metadata: "<c01 level=\"series\" id=\"d1e519\">\n  <did>\n    <unitt...", rels_ext: nil, solr: nil, dc: nil, rels_int: nil, discoverability: nil, indexing_scenario_id: 1, level: "series", ead_id_att: "d1e9309", parent_ead_ref_id: 9207, ead_ref_id: 9208, availability_policy_id: nil, date_dl_ingest: nil, date_dl_update: nil, use_right_id: nil, master_files_count: 0, automation_messages_count: 0, exemplar: "000008670_0001.tif", ancestry: "14752", pids_depth_cache: "uva-lib:1331040/uva-lib:1331041", ead_id_atts_depth_cache: "viu00001/d1e519", include_in_dl: false, exclude_in_dl: true, master_file_discoverability: false> 
1.9.3p125 :445 > list[0]==Component.find(14753)
  Component Load (0.5ms)  SELECT `components`.\* FROM `components` WHERE `components`.`id` = 14753 LIMIT 1
 => true 
1.9.3p125 :446 > Component.find(14753).ead_id_att
  Component Load (0.5ms)  SELECT `components`.\* FROM `components` WHERE `components`.`id` = 14753 LIMIT 1
 => "d1e519" 
1.9.3p125 :447 >

**Comment by louffoster** [comment]
components read-only and to be retired. closing
