### ISSUE TITLE
Create Report to Check for Valid Data

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#77]
Ideally, I would like to create a series of rake tasks to test for validity of information.  These test will not check of an object is valid, per se, but whether the data is conformant to norms.  Examples include:
- Bibls without Units
- Bibls with catalog keys but no call number
- Units without MasterFile objects
- Bibls with expired barcodes
- Customers without Orders
- Orders without Units

**Comment by louffoster** [comment]
added tasks for this. Each returns a CSV report. The tasks:

```
rails validate:call_number               # Generate a report of SirsiMetadata records that have a catalog key but no call number
rails validate:customers                 # Generate report of customers without orders
rails validate:metadata                  # Generate report of SIRSI metadata without units
rails validate:orders                    # Generate report of orders without units
rails validate:units                     # Generate report of units without master files
```

Commit 94951aeeff35742763a2bd84ada910e62121ee74
