### ISSUE TITLE
Total Transcription Loosing UTF encoding

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#90]
Look at this for an example:
http://fedora-prod02.lib.virginia.edu:8080/fedora/objects/uva-lib%3A1312610/datastreams/solrArchive/content

The umlaut is rendered accurately everywhere else, but in text_searchable.  It happenes that in lib/hydra.rb method for creating Solr documents the information for total\* are passed as params.  Could Saxon be having difficulty understanding UTF characters passed over HTTP?  Is HTTP not transporting UTF natively?

**Comment by louffoster** [comment]
Closing for a few reasons: 1. the transform is no longer used, 2. I think the text searchable is explicitly stripped of special characters like this to improve hit rates on searches - don't force users to type the umlaut
