### ISSUE TITLE
Book in DL Needs Barcodes

### ISSUE THREAD

**Issue by acurley** [uvalib/tracksys#91]
https://tracksys.lib.virginia.edu/admin/bibls/14117

I put this into the DL but it appears that we have digitized volume 17, one of 19 volumes attached to this MARC record.  I don't know if you pursued this with Special Collections already; there is no note to that effect in Tracksys.  If they have no objection, we should barcode them individually, fix the Bibl record and update the DL object.

**Comment by louffoster** [comment]
this has barcodes
