### ISSUE TITLE
extend tracksys to allow amending of finding aids

### ISSUE THREAD

**Issue by MatthewStephens** [uvalib/tracksys#97]
AC recently manually added 4 components to viu03319, using MSS 2672-g.  We should add a few features to tracksys to:
1. append new component(s) to a guide
2. provide a form for cut & paste of MARC data
3. create EAD fragments
4. update the guide XML, possibly committing to subversion

**Comment by louffoster** [comment]
all component info will be moved out of tracksys and handled elsewhere (archivesspace). all components are read-only
